web:
  image: "gitlab/gitlab-ce:${GITLAB_VERSION}"
  restart: always
  hostname: "gitlab.${EXTERNAL_HOSTNAME}"
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url "http://gitlab.${EXTERNAL_HOSTNAME}"
      letsencrypt["enable"] = false
      puma["worker_processes"] = 2
      sidekiq["max_concurrency"] = 10
      nginx["listen_port"] = 80
      nginx["listen_https"] = false
      gitlab_rails["initial_root_password"] = "${GITLAB_ROOT_PASSWORD}"
      gitlab_rails["registry_enabled"] = true
      registry_external_url "http://registry.${EXTERNAL_HOSTNAME}"
      gitlab_rails["registry_host"] = "registry.${EXTERNAL_HOSTNAME}"
      gitlab_rails["registry_port"] = "5050"
      gitlab_rails["registry_path"] = "/var/opt/gitlab/gitlab-rails/shared/registry"
      grafana["enable"] = false
      prometheus_monitoring["enable"] = false
  ports:
    - "${GITLAB_HTTP_PORT}:80"
    - "${GITLAB_HTTPS_PORT}:443"
    - "${GITLAB_SSH_PORT}:22"
    - "${GITLAB_REGISTRY_PORT}:5050"
  volumes:
    - "${GITLAB_HOME}/config:/etc/gitlab"
    - "${GITLAB_HOME}/logs:/var/log/gitlab"
    - "${GITLAB_HOME}/data:/var/opt/gitlab"
