services:
  http-proxy:
    image: "nginx:${NGINX_VERSION}"
    volumes:
      - "./templates:/etc/nginx/templates"
      - "./html:/usr/share/nginx/html:ro"
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    env_file:
      - .env
