version: "3"
services:
  swag:
    image: "lscr.io/linuxserver/swag"
    container_name: swag
    cap_add:
      - NET_ADMIN
    volumes:
      - "./config:/config"
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
