services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    # user: uid:gid
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /home/rd/Videos/tv
        target: /tv
        read_only: true
      - type: bind
        source: /home/rd/Videos/edu
        target: /edu
        read_only: true
      - type: bind
        source: "/home/rd/Videos/Music Videos"
        target: /music_videos
        read_only: true
      - type: bind
        source: "/home/rd/Videos/Movies"
        target: /movies
        read_only: true
    restart: 'unless-stopped'
    env_file:
      - .env
